export * from "./home";
export * from "./about";
export * from "./mentor-list";
export * from "./blogs";
export * from "./privacy-policy";
export * from "./services";
export * from "./contact";
export * from "./about";
export * from "./team";
